
import { GoogleGenAI, GenerateContentResponse } from "@google/genai";
import { StyleType, CategoryType } from "./types";

export const transformSketch = async (
  base64Image: string,
  style: StyleType,
  category: CategoryType,
  promptExtra: string = ""
): Promise<string> => {
  // Use the default environment key provided.
  const ai = new GoogleGenAI({ apiKey: process.env.API_KEY });
  
  // Extract base64 data without the prefix
  const base64Data = base64Image.split(',')[1];
  
  const prompt = `
    TASK: Transform this hand-drawn sketch into a photorealistic 3D ${category} in a ${style} style.
    
    INSTRUCTIONS:
    1. Maintain the EXACT pose, proportions, silhouette, and design elements from the original sketch.
    2. Add highly detailed textures (e.g., skin, fabric, metal, stone) appropriate for a ${category}.
    3. Use professional ${style} lighting (cinematic, high-contrast, or soft as per style).
    4. The background should be a clean, slightly blurred studio environment or an atmospheric setting that complements the ${style} aesthetic.
    5. Result must look like a high-end 3D render.
    6. Do not include any text, labels, or the original sketch lines in the final output.
    
    ADDITIONAL CONTEXT: ${promptExtra}
  `;

  try {
    const response: GenerateContentResponse = await ai.models.generateContent({
      model: 'gemini-2.5-flash-image',
      contents: {
        parts: [
          {
            inlineData: {
              data: base64Data,
              mimeType: 'image/png',
            },
          },
          { text: prompt },
        ],
      },
      config: {
        imageConfig: {
          aspectRatio: "1:1"
        }
      }
    });

    let imageUrl = '';
    // Iterate through all parts to find the image part as per guidelines
    for (const part of response.candidates?.[0]?.content?.parts || []) {
      if (part.inlineData) {
        imageUrl = `data:image/png;base64,${part.inlineData.data}`;
        break;
      }
    }

    if (!imageUrl) {
      throw new Error("No image was generated by the model.");
    }

    return imageUrl;
  } catch (error: any) {
    console.error("Gemini transformation error:", error);
    throw new Error("Oh no! The magic wand is tired. Let's try again in a bit!");
  }
};
